"""
Static phone dashboard for solana_screener — renders data/latest_scan.json + the ledger
scorecard into docs/index.html, which GitHub Pages serves. Regenerated by the same
GitHub Actions run that produces the data, so the page updates every scheduled scan.

Presentation-only: no network, no scoring, no state. The only timestamps shown come from
the committed scan snapshot (scan_ts), never from wall-clock in a compute path; the
"minutes ago" counter is computed client-side in the browser.
"""
from __future__ import annotations

import html
import json
import os

import pandas as pd

import config
import ledger


def _load_scan() -> dict:
    if os.path.exists(config.SCAN_PATH):
        try:
            return json.load(open(config.SCAN_PATH))
        except Exception:
            pass
    return {"scan_ts": 0, "discovered": 0, "enriched": 0, "survivors": []}


def _ledger_scorecard() -> list[dict]:
    """Per-tier hit-rate rows for the dashboard, mirroring ledger.summary()."""
    led = ledger.load()
    rows: list[dict] = []
    if len(led) == 0:
        return rows
    led = led.copy()
    led["_tier"] = led["tier"].astype(str).where(led["tier"].astype(str).isin(["A", "B"]), "A")
    for tier in ("A", "B"):
        sub = led[led["_tier"] == tier]
        if len(sub) == 0:
            continue
        row = {"tier": tier, "n": len(sub), "horizons": {}}
        for h in ledger.HORIZ:
            r = pd.to_numeric(sub[f"ret_{h}"], errors="coerce").dropna()
            if len(r):
                row["horizons"][h] = {"n": int(len(r)),
                                      "hit": float((r > 0).mean()),
                                      "median": float(r.median())}
        row["rugged"] = float(sub["rugged_after"].astype(str).str.lower().eq("true").mean())
        rows.append(row)
    return rows


def _fmt_usd(v: float) -> str:
    v = float(v or 0)
    if v >= 1e6:
        return f"${v/1e6:.1f}M"
    if v >= 1e3:
        return f"${v/1e3:.0f}k"
    return f"${v:.0f}"


def _coin_card(s: dict) -> str:
    sym = html.escape(str(s.get("symbol", "?"))[:14])
    url = html.escape(s.get("url", ""), quote=True)
    tier = s.get("tier", "B")
    misses = "; ".join(s.get("hc_misses", [])[:2])
    badge = ('<span class="badge a">A-TIER</span>' if tier == "A"
             else f'<span class="badge b" title="{html.escape(misses, quote=True)}">B</span>')
    age = float(s.get("pair_age_min") or 0)
    age_txt = f"{age/60:.1f}h" if age >= 90 else f"{age:.0f}m"
    return f"""
    <a class="card {'atier' if tier == 'A' else ''}" href="{url}" target="_blank" rel="noopener">
      <div class="row1"><span class="sym">{sym}</span>{badge}
        <span class="score">{float(s.get('score', 0)):.0f}<small>/100</small></span></div>
      <div class="row2">
        <span>liq {_fmt_usd(s.get('liq_usd'))}</span><span>mcap {_fmt_usd(s.get('mcap'))}</span>
        <span>vol24 {_fmt_usd(s.get('vol_h24'))}</span><span>age {age_txt}</span>
      </div>
      <div class="row2">
        <span>holders {s.get('total_holders', '?')}</span><span>top10 {s.get('top10_pct', '?')}%</span>
        <span>insider-nets {float(s.get('insider_networks_pct') or 0):.0f}%</span>
        <span>creator priors {s.get('creator_prior_tokens', 0)}</span>
      </div>
      {f'<div class="miss">short of A: {html.escape(misses)}</div>' if tier != 'A' and misses else ''}
    </a>"""


def render() -> str:
    scan = _load_scan()
    survivors = sorted(scan.get("survivors", []), key=lambda s: -float(s.get("score", 0)))
    a_tier = [s for s in survivors if s.get("tier") == "A"]
    b_tier = [s for s in survivors if s.get("tier") != "A"]
    card_html = ("".join(_coin_card(s) for s in a_tier)
                 or '<div class="empty">No A-tier coins this scan. Most scans have none '
                    '— that is the filter doing its job, not a malfunction.</div>')
    b_html = ("".join(_coin_card(s) for s in b_tier)
              or '<div class="empty">No B-tier survivors this scan.</div>')

    sc_rows = ""
    for row in _ledger_scorecard():
        label = "A (alerted)" if row["tier"] == "A" else "B (silent control)"
        cells = ""
        for h in ledger.HORIZ:
            hz = row["horizons"].get(h)
            cells += (f"<td>{hz['hit']*100:.0f}% / {hz['median']*100:+.0f}%</td>"
                      if hz else "<td>·</td>")
        sc_rows += (f"<tr><td>{label}</td><td>{row['n']}</td>{cells}"
                    f"<td>{row['rugged']*100:.0f}%</td></tr>")
    scorecard = (f"""<table><tr><th>tier</th><th>n</th>
        {''.join(f'<th>{h}</th>' for h in ledger.HORIZ)}<th>rugged</th></tr>{sc_rows}</table>
        <p class="note">cells = hit-rate / median return once a horizon matures. If tier A
        doesn't clearly beat tier B, the A-band is not adding signal.</p>"""
                 if sc_rows else '<p class="note">No matured ledger rows yet.</p>')

    return f"""<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="refresh" content="900">
<title>solana_screener</title>
<style>
  :root {{ color-scheme: dark; }}
  * {{ box-sizing: border-box; margin: 0; }}
  body {{ background: #0d1117; color: #e6edf3; font: 16px/1.45 -apple-system, "SF Pro Text",
         Segoe UI, Roboto, sans-serif; padding: 16px; max-width: 640px; margin: 0 auto; }}
  h1 {{ font-size: 20px; }} h2 {{ font-size: 15px; color: #8b949e; margin: 22px 0 8px;
       text-transform: uppercase; letter-spacing: .06em; }}
  .stamp {{ color: #8b949e; font-size: 13px; margin: 4px 0 14px; }}
  .card {{ display: block; background: #161b22; border: 1px solid #21262d; border-radius: 12px;
          padding: 12px 14px; margin-bottom: 10px; text-decoration: none; color: inherit; }}
  .card.atier {{ border-color: #2ea043; box-shadow: 0 0 0 1px #2ea04355; }}
  .row1 {{ display: flex; align-items: baseline; gap: 10px; }}
  .sym {{ font-weight: 700; font-size: 18px; }}
  .score {{ margin-left: auto; font-weight: 700; font-size: 18px; color: #58a6ff; }}
  .score small {{ color: #8b949e; font-weight: 400; }}
  .badge {{ font-size: 11px; font-weight: 700; padding: 2px 7px; border-radius: 999px; }}
  .badge.a {{ background: #2ea043; color: #fff; }} .badge.b {{ background: #30363d; color: #8b949e; }}
  .row2 {{ display: flex; flex-wrap: wrap; gap: 4px 14px; color: #8b949e; font-size: 13px;
          margin-top: 6px; }}
  .miss {{ color: #d29922; font-size: 12px; margin-top: 6px; }}
  .empty {{ color: #8b949e; background: #161b22; border: 1px dashed #30363d; border-radius: 12px;
           padding: 14px; font-size: 14px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th, td {{ text-align: left; padding: 5px 6px; border-bottom: 1px solid #21262d; }}
  th {{ color: #8b949e; font-weight: 600; }}
  .note {{ color: #8b949e; font-size: 12px; margin-top: 8px; }}
  footer {{ color: #6e7681; font-size: 12px; margin: 26px 0 8px; line-height: 1.5; }}
</style></head><body>
<h1>solana_screener</h1>
<div class="stamp">scanned {scan.get('discovered', 0)} · enriched {scan.get('enriched', 0)} ·
  {len(survivors)} passed gates · <span id="ago" data-ts="{scan.get('scan_ts', 0)}">…</span>
  · auto-reloads every 15&nbsp;min</div>
<h2>A-tier (alerted)</h2>{card_html}
<h2>B-tier survivors (ledgered, never alerted)</h2>{b_html}
<h2>Honest scorecard (A vs B)</h2>{scorecard}
<footer>{html.escape(config.FOOTER)} Ranked by survival-quality score, NOT predicted ROI —
insider presence predicts dumps, not pumps.</footer>
<script>
  const el = document.getElementById('ago'), ts = +el.dataset.ts * 1000;
  function tick() {{
    if (!ts) {{ el.textContent = 'no scan yet'; return; }}
    const m = Math.max(0, Math.round((Date.now() - ts) / 60000));
    el.textContent = 'updated ' + (m < 60 ? m + ' min ago' : (m/60).toFixed(1) + ' h ago');
    if (m > 150) el.style.color = '#f85149';   // stale => the cloud job is broken
  }}
  tick(); setInterval(tick, 30000);
</script>
</body></html>"""


def main() -> None:
    os.makedirs(config.DOCS_DIR, exist_ok=True)
    out = os.path.join(config.DOCS_DIR, "index.html")
    with open(out, "w") as f:
        f.write(render())
    print(f"dashboard written: {out}")


if __name__ == "__main__":
    main()
